<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>2099</title>
    <link rel="shortcut icon" href="img/favicon.svg" type="image/x-icon">
    <link rel="stylesheet" href="css/style.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
  </head>
  <body>
    <div class="container-body">
      <header>
            <h1>Defuse the bomb</h1>
            <p>賽博朋克</p>
      </header>
      <main>
        <div class="container-main">
          <p class="text-white">
            No final, o destino de Utashinai e de seus habitantes está em suas mãos. Será que você conseguirá desarmar 
            todas as bombas a tempo e descobrir a verdade por trás dos ataques? Ou Utashinai sucumbirá à violência e 
            ao caos do mundo cyberpunk? A escolha é sua.
          </p>
          <div class="d-flex justify-content-center mt-5">
            <a href="page5.phtml" class="btn btn-sm btn-danger mx-3">Back</a>
            <a href="page7.php" class="btn btn-sm btn-danger mx-3">Next</a>
          </div>   
        </div>
      </main>
             
    </div><!-- Fim container -->

    <footer class="text-center fixed-bottom pb-5 m-0 ps-3">
      2099
    </footer>

    <script src="js/script.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
  </body>
</html>